# KAMUI 4D Codex CLI 標準コマンド設定
# https://github.com/your-org/codex-cli

commands:
  # D3: テスト実行（並列 worktree で同時実行可）
  test:
    description: "Run all tests with coverage"
    run: |
      echo "=== Running Spell tests ==="
      DATABASE_URL="postgres://spell_test:spell_test@localhost:5432/spell_test" \
      cargo test --all-features -- --nocapture

  # ビルド（リリースビルド）
  build:
    description: "Build release binary"
    run: |
      echo "=== Building Spell (release) ==="
      DATABASE_URL="postgres://spell_test:spell_test@localhost:5432/spell_test" \
      SQLX_OFFLINE=true cargo build --release

  # 開発サーバー起動
  dev:
    description: "Start development server with watch"
    run: |
      echo "=== Starting Spell dev server ==="
      DATABASE_URL="postgres://spell_test:spell_test@localhost:5432/spell_test" \
      cargo watch -x run

  # デプロイ（Fly.io）
  deploy:
    description: "Deploy to Fly.io"
    run: |
      echo "=== Deploying Spell to Fly.io ==="
      timeout 900 flyctl deploy --remote-only --app spell-platform

  # Lint & Format
  lint:
    description: "Run clippy and fmt check"
    run: |
      echo "=== Running linters ==="
      DATABASE_URL="postgres://spell_test:spell_test@localhost:5432/spell_test" \
      cargo clippy --all-targets --all-features -- -D warnings
      cargo fmt -- --check

  # マイグレーション実行
  migrate:
    description: "Run database migrations"
    run: |
      echo "=== Running migrations ==="
      DATABASE_URL="postgres://spell_test:spell_test@localhost:5432/spell_test" \
      sqlx migrate run

# ワークフロー定義（複数コマンドの組み合わせ）
workflows:
  # フル検証（CI相当）
  ci:
    description: "Full CI workflow"
    steps:
      - migrate
      - lint
      - test
      - build

  # 即デプロイ（テスト→ビルド→デプロイ）
  ship:
    description: "Test, build, and deploy"
    steps:
      - test
      - build
      - deploy
