name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    name: Lint & Typecheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/spell"
        run: pnpm prisma generate

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier check
        run: pnpm format:check

      - name: Run TypeScript typecheck
        run: pnpm typecheck

  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: lint-and-typecheck
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/spell"
        run: pnpm prisma generate

      - name: Build
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/spell"
          STRIPE_SECRET_KEY: "sk_test_dummy_key_for_build"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: "dummy_secret_for_build_only"
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next/
          retention-days: 7
