name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # Only deploy if CI passed
    needs: []
    steps:
      - uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --remote-only --app spell-platform
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Health Check
        run: |
          set -e
          PRIMARY=https://api.magicspell.io/healthz
          FALLBACK=https://spell-platform.fly.dev/healthz

          for i in {1..60}; do
            for URL in "$PRIMARY" "$FALLBACK"; do
              BODY=$(curl -sf "$URL" || true)
              if [ -n "$BODY" ] && echo "$BODY" | jq -e '.status=="ok"' >/dev/null 2>&1; then
                echo "✅ Deployment healthy at $URL"
                exit 0
              fi
            done
            sleep 5
          done
          echo "❌ Deployment failed - API health check failed"
          exit 1

      - name: Verify Metrics
        run: |
          METRICS=$(curl -s https://spell-platform.fly.dev/metrics)
          if echo "$METRICS" | grep -q "spell_cast_total"; then
            echo "✅ Metrics endpoint available"
          else
            echo "❌ Metrics endpoint not working"
            exit 1
          fi
